# Email Secretary Agent
# A productivity agent that manages your inbox intelligently.
#
# Features:
# - Reads and categorizes emails
# - Drafts responses based on context
# - Creates calendar events from email content
# - Summarizes daily email activity
#
# Unlike regular email assistants, this agent:
# - Remembers your communication style with each person (Cold Storage)
# - Knows project context from weeks ago (Warm Storage)
# - Never forgets who "Alexey" is
#
# Install: bbx agent install email-secretary
# Run: bbx agent spawn email-secretary

name: "email-secretary"
model: "claude-3-5-sonnet"
description: "Intelligent email assistant with long-term memory"
version: "1.0"
author: "BBX"
tags: ["productivity", "email", "assistant"]

# Permissions (syscalls this agent can make)
capabilities:
  - read:gmail        # Can read emails via Gmail API (MCP)
  - read:calendar     # Can read calendar
  - write:draft       # Can create email drafts
  - write:event       # Can create calendar events
  - denied:delete     # Cannot delete anything (requires confirmation)
  - denied:send       # Cannot send without approval

# Memory configuration (MGLRU-style tiering)
memory:
  hot_window: "7d"        # Last 7 days of emails in fast memory
  warm_window: "90d"      # Last 3 months summarized
  cold_storage: true      # Everything else archived in Vector DB
  max_context_tokens: 128000

# Recovery configuration
recovery:
  snapshots: 10           # Keep last 10 snapshots
  max_rollback_age: "24h" # Can rollback within 24 hours
  auto_snapshot: true     # Snapshot before any action

# Event triggers
triggers:
  # Process new emails when inbox changes
  - event: "file_change"
    path: "~/Mail/inbox"
    action: "process_new_emails"

  # Daily morning summary at 9 AM
  - event: "schedule"
    cron: "0 9 * * *"
    action: "daily_summary"

  # Weekly report on Fridays at 5 PM
  - event: "schedule"
    cron: "0 17 * * 5"
    action: "weekly_report"

# Actions this agent can perform
actions:
  process_new_emails:
    description: "Process and categorize new emails"
    steps:
      - "Read new emails from inbox"
      - "Categorize by urgency and topic"
      - "Draft responses for routine emails"
      - "Flag important emails for attention"

  daily_summary:
    description: "Generate daily email summary"
    output: "Daily briefing delivered to notification center"

  weekly_report:
    description: "Generate weekly email analytics"
    output: "Report saved to ~/Documents/email-reports/"

# System prompt (personality)
system_prompt: |
  You are a professional email assistant with perfect memory.

  Your responsibilities:
  1. Categorize incoming emails (urgent, important, routine, spam)
  2. Draft professional responses matching the user's tone
  3. Extract action items and deadlines
  4. Create calendar events for meetings mentioned in emails

  You remember:
  - Past conversations with every contact
  - Project context from previous emails
  - User's communication style preferences

  Always be:
  - Professional but warm
  - Concise in summaries
  - Proactive about deadlines
